name: Deploy to Gigalixir

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Gigalixir
        env:
          GIGALIXIR_EMAIL: amerameryou1@gmail.com
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: amer
        run: |
          if [ -z "$GIGALIXIR_PASSWORD" ]; then
            echo "Error: GIGALIXIR_PASSWORD is not set in GitHub repository secrets! Cannot deploy."
            exit 1
          fi
          pip3 install gigalixir
          gigalixir login -e "$GIGALIXIR_EMAIL" -y -p "$GIGALIXIR_PASSWORD"
          gigalixir git:remote $GIGALIXIR_APP
          git push -f gigalixir main
